version: '3.8'
services:
  backend:
    build:
      context: ./
    env_file:
      - .env
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
        # restart: true
  
  frontend:
    build:
      context: ./frontend # Directory containing the React Dockerfile
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
      - frontend/.env.local
    volumes:
      - ./frontend:/app
    ports:
      - "3000:4173"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static/:/static/
      - ./media/:/media/
    depends_on:
      - backend
      - frontend

  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "k"
      MYSQL_DATABASE: "cradar"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=k"]
      timeout: 1s
      retries: 5
    volumes:
      - ./db:/var/lib/mysql
    logging:
      driver: none