# Generated by Django 4.2.3 on 2024-05-09 14:34

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_block_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplateType',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_template_types', to='api.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_templates', to='api.notetemplatetype'),
        ),
    ]
