# Generated by Django 4.2.3 on 2024-06-17 13:58

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import shortuuid.django_fields

from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

def initialize_tag_vector(apps, schema_editor):
    Tag = apps.get_model("api", "Tag")
    tags = Tag.objects.all()
    names = [tag.name for tag in tags]
    vectors = embeddings.embed_documents(names)
    tags_to_update = []
    for i, tag in enumerate(tags):
        tag.vector = vectors[i]
        tags_to_update.append(tag)
    Tag.objects.bulk_update(tags_to_update, ["vector"])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_notetype_project_alter_takeawaytype_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagBoard',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='tag',
            name='vector',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.project'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=pgvector.django.HnswIndex(fields=['vector'], name='tag-vector-index', opclasses=['vector_ip_ops']),
        ),
        migrations.AddField(
            model_name='tagboard',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tag_boards', to='api.project'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='api.tagboard'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'tag_board')},
        ),
        migrations.AlterUniqueTogether(
            name='tagboard',
            unique_together={('name', 'project')},
        ),
        migrations.RunPython(initialize_tag_vector),
        migrations.AlterField(
            model_name='tag',
            name='vector',
            field=pgvector.django.VectorField(dimensions=1536, null=False),
        ),
    ]
