# Generated by Django 4.2.3 on 2024-06-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_googledriveuser_googledriveoauthstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="google_drive_file_timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
