# Generated by Django 4.2.3 on 2024-07-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_stripesubscription_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutorial',
            field=models.JSONField(default=dict),
        ),
    ]
