# Generated by Django 4.2.3 on 2024-07-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_user_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='default',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
