# Generated by Django 4.2.3 on 2024-01-02 23:50

import json

from django.db import migrations, models


def convert_summary_string_to_list(apps, schema_editor):
    Note = apps.get_model("note", "Note")
    for note in Note.objects.all():
        note.summary = json.dumps([note.summary])
        note.save()


def revert_convert_summary_string_to_list(apps, schema_editor):
    Note = apps.get_model("note", "Note")
    for note in Note.objects.all():
        note.summary = json.loads(note.summary)[0]
        note.save()


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0026_alter_note_file_type"),
    ]

    operations = [
        migrations.RunPython(
            code=convert_summary_string_to_list,
            reverse_code=revert_convert_summary_string_to_list,
        ),
        migrations.AlterField(
            model_name="note",
            name="summary",
            field=models.JSONField(default=list),
        ),
    ]
