name: Test

on:
  push:
    branches:
    - main
jobs:
  Deployment:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: .
          remote_path: /home/ubuntu/cradar-backend
          remote_host: 52.220.178.82
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEYS }}
