name: Deploy to Dev

on:
  push:
    branches:
    - dev

jobs:
  deploy-kizunna-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: rsync kizunna
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete --exclude="frontend" --exclude="media" --exclude="db" --exclude=".env" --exclude="**/__pycache__" --exclude="credentials"
          path: .
          remote_path: /home/ubuntu/kizunna-backend
          remote_host: ${{ vars.IP_ADDR_KIZUNNA_DEV }}
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY_KIZUNNA_DEV }}

      - name: running kizunna
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.IP_ADDR_KIZUNNA_DEV }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY_KIZUNNA_DEV }}
          port: 22
          script: |
            cd /home/ubuntu/kizunna-backend
            docker image prune -f
            docker builder prune -af
            docker-compose build backend
            docker-compose stop
            docker-compose up -d

      - name: setting crontab to auto restart unhealthy containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.IP_ADDR_KIZUNNA_DEV }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY_KIZUNNA_DEV }}
          port: 22
          script: |
            echo "* * * * * docker ps -q -f health=unhealthy | xargs --no-run-if-empty docker restart" > /tmp/cronjob.tmp
            crontab /tmp/cronjob.tmp
            rm /tmp/cronjob.tmp
